#!/usr/bin/env bash
# fixing issues arising from using Docker 
# make the apache server return Hello Holberton

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
sudo echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
