#!/usr/bin/env bash
# insa=tall load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend Sng4
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 6077-web-01 3.90.27.27:80 check
    server 6077-web-02 184.72.164.90:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
