#!/usr/bin/env bash
# servers are the piece of software generatig and serving HTML pages
# installing nginx on the web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
service nginx restart
