#!/usr/bin/env bash
# servers are the piece of software generaing and serving HTML pages
# installing nginx on the web-01

set -e
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=LHd447EafFY permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
